### ISSUE TITLE
Full port of Java GCM code with tests

### ISSUE THREAD

**Issue by christiaan** [lkorth/php-gcm#11]
Apparently we both embarked on the same mission to port the GCM code at around the same time.

Instead of doing a loosly port I did a full port including the unittests.

Would you be interested to see if we can merge the two efforts?

**Comment by lkorth** [comment]
Sure. I didn't see your repo, but if you would like to contribute changes and unit tests to php-gcm feel free to submit pull requests. I'd be willing to setup travis as well once there are tests.

**Comment by christiaan** [comment]
How does this package compare to the [GCMApplicationService](https://github.com/Web-Power/GCMApplicationServer)?

GCMApplicationService has these properties.

- Is a full port of the Java GCM implementation and thus compatible with the documentation of the official package.
- Has all the unit tests the Java GCM implementation has ported to PHPUnit tests.
- Has a interchangeable transport layer which by default uses the Buzz package which supports both Curl and file_get_contents.

Why did you choose to do a loose port? Which functionality of your package is better/has a better api than the Java API? Where did you deviate and what extra value does it bring?

**Comment by lkorth** [comment]
php-gcm is very close to Google's Java GCM library, the only difference should be the underlying network requests use PHP's curl and a few stylistic things that didn't translate well to PHP. Existing documentation should work fine. php-gcm has not however ported over the unit tests.
