### ISSUE TITLE
Usage guide

### ISSUE THREAD

**Issue by zedzag** [lkorth/php-gcm#13]
Hi thanks a lot for this but I'm hoping I can ask a newbie question: 

I know I have to create the files in my server's folder. But how would I implement sending, would I incorporate the "Usage" section of the readme in my regular php file? If so what are the $collapsekey and $payloaddata supposed to be? I'm assuming payloaddata is the actual message, but not sure what collapsekey would be.

**Comment by lkorth** [comment]
Yes, the [Usage](https://github.com/lkorth/php-gcm#usage) section in the README is a simple example of how to send a gcm message to a device. 

I recommend you read the [Cloud Messaging Guide](https://developers.google.com/cloud-messaging/downstream) to better understand the protcol and what collapse keys and payloads are.
