### ISSUE TITLE
Composer.json

### ISSUE THREAD

**Issue by zedzag** [lkorth/php-gcm#14]
I'm trying out your php port of Google GCM, i copy pasted the files in the src directory to my servers directory where all my other php files are housed. I've added the line:

```json
"require": {
    "php-gcm/php-gcm": "1.1.0"
}
```

in the composer.json file you already had created. I am stuck in the step that says run composer.json

How do I run it when its housed in my server? I've tried opening it in the browser but that just gives me the date within it.

**Comment by lkorth** [comment]
Composer does not work like that, composer is a dependency management system that downloads, manages and loads your dependencies for you. I recommend reading about [how composer works](https://getcomposer.org/doc/00-intro.md) before trying to use php-gcm.
