### ISSUE TITLE
how to set notification payload?

### ISSUE THREAD

**Issue by shwhl** [lkorth/php-gcm#18]
how to set `notification` payload?

**Comment by lkorth** [comment]
Are you refering to https://developers.google.com/cloud-messaging/http-server-ref#notification-payload-support ?

**Comment by shwhl** [comment]
Yes, I only see the `data` payload in your code.

**Comment by lkorth** [comment]
Correct, there is not currently support for sending notifications.

**Comment by lkorth** [comment]
It is something I plan to add soon after the refactor to use only json requests is finished.

**Comment by shwhl** [comment]
Thank you!

**Comment by lkorth** [comment]
d7311333793ab8f4c104cae43893f52f112bce25 added initial support for the notification payload.
