### ISSUE TITLE
Simultaneous sending limit

### ISSUE THREAD

**Issue by kenvunz** [lkorth/php-gcm#20]
GCM has a hard limit of 1000 device ids per request to their server. Just wondering if your library has taken care of this details? Or do we need to `array_chunk` ourselves?

Cheers
Ken

**Comment by lkorth** [comment]
It does not currently handle splitting the array into chunks, but it would be a very useful feature to have. If you're interested in adding support for it, I would be very happy to review and merge the pull request.

**Comment by chancezeus** [comment]
After seeing your post (and realizing I already encountered the same requirement) I implemented a version that does just that. The only (major) difference to the current implementation is that it returns an AggregateResult class which encapsulates the separate MulticastResults from each chunk.
The AggregateResult class contains exactly the same methods as the MulticastResult class, so it should be a drop-in replacement.
Check here: https://github.com/chancezeus/php-gcm/commit/e0979ae7f98a4976adbcaa31f5b8fb864875d4af

**Comment by kenvunz** [comment]
👍🏻 awesome, i'll check it out
On Wed, 13 Apr 2016 at 9:47 AM, Mark van Beek <notifications@github.com>
wrote:

> After seeing your post (and realizing I already encountered the same
> requirement) I implemented a version that does just that. The only (major)
> difference to the current implementation is that it returns an
> AggregateResult class which encapsulates the separate MulticastResults from
> each chunk.
> The AggregateResult class contains exactly the same methods as the
> MulticastResult class, so it should be a drop-in replacement.
> Check here: chancezeus@e0979ae
> <https://github.com/chancezeus/php-gcm/commit/e0979ae7f98a4976adbcaa31f5b8fb864875d4af>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/lkorth/php-gcm/issues/20#issuecomment-209116714>
>
-- 

KEN VU / DEVELOPER / GLADEYE <http://www.gladeye.co.nz/> / P +64 9 3543564
 / M +64 21 2800 450 /
79 ST GEORGES BAY, PARNELL, AUCKLAND, NEW ZEALAND

**Comment by lkorth** [comment]
Fixed in 647138d1a34b3b57dc980a56f1544713d5c196fa
