### ISSUE TITLE
Composer installs old version

### ISSUE THREAD

**Issue by henningtillmann** [lkorth/php-gcm#24]
Hey there,

when I use require lkorth "php-gcm/php-gcm": "^1.1.1" I always get an old version from 2013 with no support for multi-device push messages. Is the package name correct?

Thanks,
Henning

**Comment by lkorth** [comment]
Yes, that is the correct package name. The exact line to include via composer is [in the README](https://github.com/lkorth/php-gcm#install) and you can also find [1.1.1 on Packagist](https://packagist.org/packages/php-gcm/php-gcm#1.1.1).

**Comment by henningtillmann** [comment]
@lkorth I'm sorry, but that's incorrect. I used the exact line that's in the README file and it gives me old files.

**Comment by henningtillmann** [comment]
@lkorth This is what happens when I run composer.phar update

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing php-gcm/php-gcm (1.1.1)
    Downloading: 100%         

Writing lock file
Generating autoload files
```

When I open e.g. Sender.php I get an old file from 2013:
nano vendor/php-gcm/php-gcm/src/PHP_GCM/Sender.php

**Comment by lkorth** [comment]
No, that's exactly correct, look at the code in the tag for 1.1.1, you're getting 1.1.1. What you want to get is `dev-master` instead of 1.1.1.

**Comment by henningtillmann** [comment]
@lkorth Oh! I'm sorry! I thought that multi device support was included in 1.1.1 and I was irritated when I saw that old file.

**Comment by lkorth** [comment]
Nope! I haven't made a release in a while since a few of the changes are breaking changes. Once a few more things finalize there will be a 2.0.0 release which will include everything. For now `dev-master` should be fine, it just has some breaking API changes which prevent minor releases.

**Comment by lkorth** [comment]
I'll update the README to mention `dev-master` for those wishing to use the latest.

**Comment by lkorth** [comment]
🎉 https://github.com/lkorth/php-gcm#latest
