### ISSUE TITLE
Support for Firebase Cloud Messaging (FCM)

### ISSUE THREAD

**Issue by delitestudio** [lkorth/php-gcm#29]
Google has introduced Firebase Cloud Messaging (FCM) as a replacement of GCM and started to [strongly encourage to upgrade](https://developers.google.com/cloud-messaging/faq):

> Is GCM going to be deprecated?
> 
> We will continue to support the current version of GCM Android and iOS SDKs because we know a lot of developers are using GCM SDKs today to handle notifications, and client app upgrade takes time.
> 
> But all new client-side features will be added to FCM SDKs only moving forward. You are strongly encouraged to upgrade to FCM SDKs.

Do you think Firebase Cloud Messaging will be supported by your library or as a new php-fcm project?

**Comment by auchri** [comment]
It works already (for me), just change GCM_ENDPOINT in [Sender.php](https://github.com/lkorth/php-gcm/blob/master/src/PHP_GCM/Sender.php).

It works also _without_ changing the endpoint.
