### ISSUE TITLE
I have a question about php-gcm.

### ISSUE THREAD

**Issue by kimokhun** [lkorth/php-gcm#31]
I'm using the PHP CI framework should be sure to use the composer?
Is there any way to run without using the composer?

If you have more detailed usage it seems to be good. 

$ Sender = new Sender ($ gcmApiKey);
$ Message = new Message ($ collapseKey, $ payloadData);

try {
     $ Result = $ sender-> send ($ message, $ deviceRegistrationId, $ numberOfRetryAttempts);
} Catch (\ InvalidArgumentException $ e) {
     // $ DeviceRegistrationId was null
} Catch (PHP_GCM \ InvalidRequestException $ e) {
     // Server returned HTTP code other than 200 or 503
} Catch (\ Exception $ e) {
     // Message could not be sent
}

What methods can be used to add a phrase in getBodyLocKey?

**Comment by lkorth** [comment]
Composer is recommended, but it is possible to download the PHP files and include them yourself to use it.

Take a look at the PHP doc for [`bodyLocKey`](https://github.com/lkorth/php-gcm/blob/732d13ce427a8fc2feb4eac858c7e677d94e4033/src/PHP_GCM/Notification.php#L168-L173) and [`bodyLocArgs`](https://github.com/lkorth/php-gcm/blob/732d13ce427a8fc2feb4eac858c7e677d94e4033/src/PHP_GCM/Notification.php#L185-L190) for more information about using those methods.
