### ISSUE TITLE
"Received error code 0 from GCM Service" if no "CURLOPT_SSL_VERIFYPEER" to false

### ISSUE THREAD

**Issue by timmy78** [lkorth/php-gcm#5]
Hi

I used the library in local.
When I send a message, I receive the error : "Received error code 0 from GCM Service".

But when in the code I put the option *CURLOPT_SSL_VERIFYPEER* to *false* in [Sender.php](https://github.com/lkorth/php-gcm/blob/master/src/PHP_GCM/Sender.php#L128)  it works.
```curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);```

Why ?

Thank you !

**Comment by lkorth** [comment]
You may have outdated, or incorrect certificates on the box you're running this from. What is the output of `curl https://android.googleapis.com/gcm/send` on the same box?

**Comment by timmy78** [comment]
The response is "false" and the status is "0".

How to correct it ? 

All the ports are opened.
I used this [bundle](https://github.com/richsage/RMSPushNotificationsBundle) last time (which use [kriswallsmith/buzz lib](kriswallsmith/buzz)) and it worked on the box.

Thank you !

**Comment by lkorth** [comment]
You may want to add the verbose flag to see what is happening. `curl -v https://android.googleapis.com/gcm/send`. It appears that there is an underlaying issue with curl and SSL on your box that you will need to fix in order to use curl in PHP securely.

**Comment by lkorth** [comment]
Closing old issue.
