### ISSUE TITLE
Why PHP version 5.3.29?

### ISSUE THREAD

**Issue by dimrsilva** [lkorth/php-gcm#8]
Hi,

It is not a issue, just a question.

I need to run this package on a PHP 5.3.10 installation. Then, before doing anything, could anyone tell me why this package requires PHP 5.3.29?

**Comment by lkorth** [comment]
As far as I know there isn't any particular reason to depend specifically on `5.3.29`, it was the version @bishopb set in #6. If you would like to test it on `5.3.10` and it works, I can adjust the version.

**Comment by dimrsilva** [comment]
I will test my application on `5.3.10`, if it works, I tell you, so that you can adjust it.

**Comment by dimrsilva** [comment]
Well, finally I could test my app, it is running on PHP 5.3.10 and it works fine.

**Comment by lkorth** [comment]
Reduced the minimum version in fdd57ec3f79fd5a7f0936d695a977c27b22ea67a and tagged it as `1.1.1`. It should be available on composer soon.
